name: Simplified Debugging Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node.js v14 which is supported by Hardhat

      - name: Check Node.js Version
        run: node -v

      - name: Debug Private Key Length
        run: echo "Private Key Length: ${#DEPLOYER_PRIVATE_KEY}"
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

      - name: Print Private Key Start and End (Safe)
        run: echo "Key start: ${DEPLOYER_PRIVATE_KEY:0:4}, Key end: ${DEPLOYER_PRIVATE_KEY: -4}"
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          
      - name: Basic Hardhat Version Check
        run: |
          npm install --save-dev hardhat@latest
          npx hardhat --version

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Basic Hardhat Command
        run: npx hardhat help
