name: Deploy Contract

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd hardhat
        npm install

    - name: Log Secret Values (for debugging)
      run: |
        echo "Preparing to deploy..."
        echo "INFURA_PROJECT_ID: ${INFURA_PROJECT_ID:0:4}...${INFURA_PROJECT_ID: -4} (Length: ${#INFURA_PROJECT_ID} characters)"
        echo "DEPLOYER_PRIVATE_KEY: ${DEPLOYER_PRIVATE_KEY:0:6}...${DEPLOYER_PRIVATE_KEY: -4} (Length: ${#DEPLOYER_PRIVATE_KEY} characters)"
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

    - name: Compile contracts
      run: |
        cd hardhat
        npx hardhat compile
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

    - name: List contents of artifacts directory
      run: |
        cd hardhat
        ls -R artifacts/
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

    - name: Deploy Smart Contract
      run: |
        cd hardhat
        npx hardhat run scripts/deploy.js --network sepolia
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
        
    - name: Save ABI for Frontend
      run: |
        mkdir -p docs
        cp hardhat/artifacts/contracts/ImageRequest.sol/ImageRequest.json docs/
   
    - name: Verify ABI Copy
      run: |
        ls -l docs/
