name: Compile, Deploy, and Run Listener

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js 18 for compatibility

      - name: Navigate to Hardhat Project Directory
        run: cd hardhat  # Ensure you're in the correct directory

      - name: Install Dependencies
        run: |
          npm install  # Ensure package.json exists and install dependencies

      - name: Compile Smart Contracts
        run: |
          npx hardhat compile  # Compile contracts after navigating to correct directory

      - name: Run Basic Hardhat Command
        run: |
          npx hardhat help
