- name: Deploy Smart Contract
  run: |
    cd hardhat
    npx hardhat run scripts/deploy.js --network sepolia
  env:
    INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
    DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
